**Loading the python library**

In [1]:
# Necessary libraries 
import numpy as np
import pandas as pd

**Reading the data**

In [2]:
# Loading the original data set and having a peek on the content

df = pd.read_csv('Exam_Score_Prediction.csv')
df.head(10)

,student_id,age,gender,course,study_hours,class_attendance,internet_access,sleep_hours,sleep_quality,study_method,facility_rating,exam_difficulty,exam_score
0,1,17,male,diploma,2.78,92.9,yes,7.4,poor,coaching,low,hard,58.9
1,2,23,other,bca,3.37,64.8,yes,4.6,average,online videos,medium,moderate,54.8
2,3,22,male,b.sc,7.88,76.8,yes,8.5,poor,coaching,high,moderate,90.3
3,4,20,other,diploma,0.67,48.4,yes,5.8,average,online videos,low,moderate,29.7
4,5,20,female,diploma,0.89,71.6,yes,9.8,poor,coaching,low,moderate,43.7
5,6,23,male,b.tech,3.48,65.4,yes,4.2,good,mixed,low,moderate,58.2
6,7,17,female,b.tech,1.35,69.0,yes,7.4,average,online videos,high,hard,53.7
7,8,22,male,b.sc,5.48,51.1,yes,8.2,poor,self-study,low,moderate,47.3
8,9,18,other,bca,2.89,92.0,yes,6.6,poor,self-study,low,easy,44.9
9,10,17,male,bba,6.77,44.8,yes,9.8,average,group study,high,moderate,77.7

In [3]:
# Getting some info about the data, Dtype and shape

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   student_id        20000 non-null  int64
 1   age               20000 non-null  int64
 2   gender            20000 non-null  object
 3   course            20000 non-null  object
 4   study_hours       20000 non-null  float64
 5   class_attendance  20000 non-null  float64
 6   internet_access   20000 non-null  object
 7   sleep_hours       20000 non-null  float64
 8   sleep_quality     20000 non-null  object
 9   study_method      20000 non-null  object
 10  facility_rating   20000 non-null  object
 11  exam_difficulty   20000 non-null  object
 12  exam_score        20000 non-null  float64
dtypes: float64(4), int64(2), object(7)
memory usage: 2.0+ MB

**Formatting tables**

In [4]:
# Replacing the undescores and white spaces to Empty spcaces, 

df.columns = df.columns.str.title().str.replace("_", "")
df.columns = df.columns.str.replace(" ", "")

# Removing the point from some categories in the course column

df['Course'] = df['Course'].str.replace('.', '', regex=False)

# Changing some categories names into a better format

df['StudyMethod'] = df['StudyMethod'].replace({
    'self-study': 'selfstudy',
    'online videos': 'online',
    'group study': 'groupstudy',
    'mixed': 'mixed'
})
df.head()

,StudentId,Age,Gender,Course,StudyHours,ClassAttendance,InternetAccess,SleepHours,SleepQuality,StudyMethod,FacilityRating,ExamDifficulty,ExamScore
0,1,17,male,diploma,2.78,92.9,yes,7.4,poor,coaching,low,hard,58.9
1,2,23,other,bca,3.37,64.8,yes,4.6,average,online,medium,moderate,54.8
2,3,22,male,bsc,7.88,76.8,yes,8.5,poor,coaching,high,moderate,90.3
3,4,20,other,diploma,0.67,48.4,yes,5.8,average,online,low,moderate,29.7
4,5,20,female,diploma,0.89,71.6,yes,9.8,poor,coaching,low,moderate,43.7

**Dropping StudentId column**

In [5]:
df = df.drop('StudentId', axis=1) # Drop the ID column

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Age              20000 non-null  int64
 1   Gender           20000 non-null  object
 2   Course           20000 non-null  object
 3   StudyHours       20000 non-null  float64
 4   ClassAttendance  20000 non-null  float64
 5   InternetAccess   20000 non-null  object
 6   SleepHours       20000 non-null  float64
 7   SleepQuality     20000 non-null  object
 8   StudyMethod      20000 non-null  object
 9   FacilityRating   20000 non-null  object
 10  ExamDifficulty   20000 non-null  object
 11  ExamScore        20000 non-null  float64
dtypes: float64(4), int64(1), object(7)
memory usage: 1.8+ MB

**Checking the Data Category for each column**

In [7]:
df['Gender'].value_counts()

Gender
other     6726
male      6695
female    6579
Name: count, dtype: int64

In [8]:
df['InternetAccess'].value_counts()

InternetAccess
yes    16988
no      3012
Name: count, dtype: int64

In [9]:
df['SleepQuality'].value_counts()

SleepQuality
average    6694
poor       6687
good       6619
Name: count, dtype: int64

In [10]:
df['FacilityRating'].value_counts()

FacilityRating
medium    6760
low       6638
high      6602
Name: count, dtype: int64

In [11]:
df['ExamDifficulty'].value_counts()

ExamDifficulty
moderate    9878
easy        6141
hard        3981
Name: count, dtype: int64

In [12]:
df['Course'].value_counts()

Course
bca        2902
ba         2896
bsc        2878
bcom       2864
bba        2836
diploma    2826
btech      2798
Name: count, dtype: int64

In [13]:
df['StudyMethod'].value_counts()

StudyMethod
selfstudy     4079
online        4069
coaching      4036
groupstudy    3922
mixed         3894
Name: count, dtype: int64

# Converting some numerical features into categorical data

# ExamScore

In [14]:
# Converting ExamScore values into grades, also creating a copy of the original dataset to keep the original data

df1 = df.copy() 
df1['Grade'] = df1['ExamScore'].apply(
    lambda x: 'A' if x >= 80 else
              'B' if x >= 70 else
              'C' if x >= 60 else
              'D' if x >= 50 else
              'F'
)

In [15]:
# Dropping ExamScore column 
df1 = df1.drop(columns=['ExamScore'])
df1.head()

,Age,Gender,Course,StudyHours,ClassAttendance,InternetAccess,SleepHours,SleepQuality,StudyMethod,FacilityRating,ExamDifficulty,Grade
0,17,male,diploma,2.78,92.9,yes,7.4,poor,coaching,low,hard,D
1,23,other,bca,3.37,64.8,yes,4.6,average,online,medium,moderate,D
2,22,male,bsc,7.88,76.8,yes,8.5,poor,coaching,high,moderate,A
3,20,other,diploma,0.67,48.4,yes,5.8,average,online,low,moderate,F
4,20,female,diploma,0.89,71.6,yes,9.8,poor,coaching,low,moderate,F

In [16]:
df1['Grade'].value_counts()

Grade
F    5404
A    3862
C    3830
D    3549
B    3355
Name: count, dtype: int64

# StudyHours

In [17]:
# Converting StudyHours into levels 

df1['StudyLevel'] = df1['StudyHours'].apply(
    lambda x: 'low' if x <= 2 else ('medium' if x <= 5 else 'high')
)

In [18]:
# Dropping StudyHours column 

df1 = df1.drop(columns=['StudyHours'])
df1.head()

,Age,Gender,Course,ClassAttendance,InternetAccess,SleepHours,SleepQuality,StudyMethod,FacilityRating,ExamDifficulty,Grade,StudyLevel
0,17,male,diploma,92.9,yes,7.4,poor,coaching,low,hard,D,medium
1,23,other,bca,64.8,yes,4.6,average,online,medium,moderate,D,medium
2,22,male,bsc,76.8,yes,8.5,poor,coaching,high,moderate,A,high
3,20,other,diploma,48.4,yes,5.8,average,online,low,moderate,F,low
4,20,female,diploma,71.6,yes,9.8,poor,coaching,low,moderate,F,low

# SleepHours

In [19]:
df1['SleepLevel'] = df1['SleepHours'].apply(
    lambda x: 'bad' if x < 5 else ('regular' if x < 7 else 'good')
)

In [20]:
# Dropping SleepHours column 

df1 = df1.drop(columns=['SleepHours'])
df1.head()

,Age,Gender,Course,ClassAttendance,InternetAccess,SleepQuality,StudyMethod,FacilityRating,ExamDifficulty,Grade,StudyLevel,SleepLevel
0,17,male,diploma,92.9,yes,poor,coaching,low,hard,D,medium,good
1,23,other,bca,64.8,yes,average,online,medium,moderate,D,medium,bad
2,22,male,bsc,76.8,yes,poor,coaching,high,moderate,A,high,good
3,20,other,diploma,48.4,yes,average,online,low,moderate,F,low,regular
4,20,female,diploma,71.6,yes,poor,coaching,low,moderate,F,low,good

# ClassAttendance

In [21]:
df1['AttendanceLevel'] = df1['ClassAttendance'].apply(
    lambda x: 'low' if x < 60 else ('medium' if x < 80 else 'high')
)

In [22]:
# Dropping SleepHours column 

df1 = df1.drop(columns=['ClassAttendance'])
df1.head()

,Age,Gender,Course,InternetAccess,SleepQuality,StudyMethod,FacilityRating,ExamDifficulty,Grade,StudyLevel,SleepLevel,AttendanceLevel
0,17,male,diploma,yes,poor,coaching,low,hard,D,medium,good,high
1,23,other,bca,yes,average,online,medium,moderate,D,medium,bad,medium
2,22,male,bsc,yes,poor,coaching,high,moderate,A,high,good,medium
3,20,other,diploma,yes,average,online,low,moderate,F,low,regular,low
4,20,female,diploma,yes,poor,coaching,low,moderate,F,low,good,medium

In [23]:
# This save and creates a New file with the cleaned dataset

df1.to_csv('Exam_Score_Cleaned_Final.csv', index=False)